### ISSUE TITLE
Interface de comunicación API-WebServer

### ISSUE THREAD

**Issue by danielospina-b** [miloac/AREMProyT2#1]
URL para obtener el cuadrado
`/cuadrado?valor=[valor]`

Respuesta JSON: 
`{valor : [valor], cuadrado : [cuadrado]}`

**Comment by miloac** [comment]
API completada, bajo la ruta "/cuadrado" recibe un número en el atributo "valor" y retorna un JSON con dicho valor y su cuadrado.
